#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xam.TastyToast.Resource", IsApplication=false)]

namespace xam.TastyToast
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int background_toast = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int confusing_toast = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int default_toast = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int error_toast = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int info_toast = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int success_toast = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int warning_toast = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public static int base_layout = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int confusingView = 2131034115;
			
			// aapt resource value: 0x7f050006
			public static int defaultView = 2131034118;
			
			// aapt resource value: 0x7f050005
			public static int defaultViewLayout = 2131034117;
			
			// aapt resource value: 0x7f050008
			public static int errorView = 2131034120;
			
			// aapt resource value: 0x7f050007
			public static int errorViewLayout = 2131034119;
			
			// aapt resource value: 0x7f050009
			public static int infoView = 2131034121;
			
			// aapt resource value: 0x7f050002
			public static int linearLayout = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int root_layout = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public static int successView = 2131034122;
			
			// aapt resource value: 0x7f050004
			public static int toastMessage = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public static int warningView = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int confusing_toast_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int default_toast_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int error_toast_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int info_toast_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int success_toast_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int warning_toast_layout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
