#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App_TastyToast.Resource", IsApplication=true)]

namespace App_TastyToast
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::xam.rebound.Resource.String.ApplicationName = global::App_TastyToast.Resource.String.ApplicationName;
			global::xam.rebound.Resource.String.Hello = global::App_TastyToast.Resource.String.Hello;
			global::xam.TastyToast.Resource.Drawable.background_toast = global::App_TastyToast.Resource.Drawable.background_toast;
			global::xam.TastyToast.Resource.Drawable.confusing_toast = global::App_TastyToast.Resource.Drawable.confusing_toast;
			global::xam.TastyToast.Resource.Drawable.default_toast = global::App_TastyToast.Resource.Drawable.default_toast;
			global::xam.TastyToast.Resource.Drawable.error_toast = global::App_TastyToast.Resource.Drawable.error_toast;
			global::xam.TastyToast.Resource.Drawable.info_toast = global::App_TastyToast.Resource.Drawable.info_toast;
			global::xam.TastyToast.Resource.Drawable.success_toast = global::App_TastyToast.Resource.Drawable.success_toast;
			global::xam.TastyToast.Resource.Drawable.warning_toast = global::App_TastyToast.Resource.Drawable.warning_toast;
			global::xam.TastyToast.Resource.Id.base_layout = global::App_TastyToast.Resource.Id.base_layout;
			global::xam.TastyToast.Resource.Id.confusingView = global::App_TastyToast.Resource.Id.confusingView;
			global::xam.TastyToast.Resource.Id.defaultView = global::App_TastyToast.Resource.Id.defaultView;
			global::xam.TastyToast.Resource.Id.defaultViewLayout = global::App_TastyToast.Resource.Id.defaultViewLayout;
			global::xam.TastyToast.Resource.Id.errorView = global::App_TastyToast.Resource.Id.errorView;
			global::xam.TastyToast.Resource.Id.errorViewLayout = global::App_TastyToast.Resource.Id.errorViewLayout;
			global::xam.TastyToast.Resource.Id.infoView = global::App_TastyToast.Resource.Id.infoView;
			global::xam.TastyToast.Resource.Id.linearLayout = global::App_TastyToast.Resource.Id.linearLayout;
			global::xam.TastyToast.Resource.Id.root_layout = global::App_TastyToast.Resource.Id.root_layout;
			global::xam.TastyToast.Resource.Id.successView = global::App_TastyToast.Resource.Id.successView;
			global::xam.TastyToast.Resource.Id.toastMessage = global::App_TastyToast.Resource.Id.toastMessage;
			global::xam.TastyToast.Resource.Id.warningView = global::App_TastyToast.Resource.Id.warningView;
			global::xam.TastyToast.Resource.Layout.confusing_toast_layout = global::App_TastyToast.Resource.Layout.confusing_toast_layout;
			global::xam.TastyToast.Resource.Layout.default_toast_layout = global::App_TastyToast.Resource.Layout.default_toast_layout;
			global::xam.TastyToast.Resource.Layout.error_toast_layout = global::App_TastyToast.Resource.Layout.error_toast_layout;
			global::xam.TastyToast.Resource.Layout.info_toast_layout = global::App_TastyToast.Resource.Layout.info_toast_layout;
			global::xam.TastyToast.Resource.Layout.success_toast_layout = global::App_TastyToast.Resource.Layout.success_toast_layout;
			global::xam.TastyToast.Resource.Layout.warning_toast_layout = global::App_TastyToast.Resource.Layout.warning_toast_layout;
			global::xam.TastyToast.Resource.String.ApplicationName = global::App_TastyToast.Resource.String.ApplicationName;
			global::xam.TastyToast.Resource.String.Hello = global::App_TastyToast.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_toast = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int confusing_toast = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_toast = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int error_toast = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int info_toast = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int success_toast = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int warning_toast = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int base_layout = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int confusingView = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int defaultView = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int defaultViewLayout = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int errorView = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int errorViewLayout = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int infoView = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int root_layout = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int showConfusingToast = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int showDefaultToast = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int showErrorToast = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int showInfoToast = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int showSuccessToast = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int showWarningToast = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int successView = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int toastMessage = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int warningView = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int confusing_toast_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int default_toast_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int error_toast_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int info_toast_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int success_toast_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int warning_toast_layout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
